### ISSUE TITLE
Unregister space from npm and please provide it if possible?

### ISSUE THREAD

**Issue by renhiyama** [breck7/space#95]
@breck7 Considering this is a very old project, not maintained anymore, better alternatives exist, would it be possible if I can get the package name for my usecase?
Considering the "used by" section that github normally shows, I dont see it here so I can assume there are no projects using it so there should be nothing to worry about anything breaking.

I have plans to create a docker alternative container like runtime library that can run on userspace without any `sudo` requirements. As such, I have thought of the name "space" and it fits quite nicely considering the galaxy/universe is a nice space and just a fun way to term it up, and for docker containers, I would name them planets. Let me know what do you think of it!

Hopefully you're active on github, and have a nice day!

**Comment by renhiyama** [comment]
Here's the link incase you needed: https://docs.npmjs.com/unpublishing-packages-from-the-registry 😅

It would be very helpful if you sir if you could unpublish it.

**Comment by breck7** [comment]
Hi, I was asked this by WesleyTodd a few years ago (https://www.npmjs.com/~wesleytodd) and gave him the package. I have no admin rights over it anymore. It looks like he did not use it, but he is the person to contact.

**Comment by renhiyama** [comment]
Ah alright. Thanks for notifying!
